enum HttpCustomStatus {
  LOGIN_BAD_EMAIL = 440,
  LOGIN_BAD_PASSWORD = 441,
  EMAIL_ALREADY_TAKEN = 442,
  NOT_FRIEND_WITH_USER = 443,
  CANNOT_SELF_FRIEND_REQUEST = 444,
  FRIEND_REQUEST_ALREADY_PENDING = 445,
}

export default HttpCustomStatus;